# Generated by Django 2.2.25 on 2022-11-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0035_auto_20220223_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoMGB2',
            fields=[
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadado_mgb2', related_query_name='metadado_mgb2', serialize=False, to='layers.Layer')),
                ('character_encoding', models.CharField(choices=[('UTF-8', 'UTF-8'), ('LATIN1', 'LATIN1')], max_length=10)),
                ('publicar', models.BooleanField(default=False)),
            ],
        ),
    ]
